### ISSUE TITLE
几个需要设置助力账号的py添加环境变量后提示"ck格式不正确，请检查"

### ISSUE THREAD

**Issue by lhj2525** [wuye999/myScripts#10]
锦鲤，财富岛提示

**Comment by lhj2525** [comment]
Traceback (most recent call last):                                                                      
  File "/jd/scripts/jd_jl.py", line 353, in <module>                                                    
    main()                                                                                              
  File "/jd/scripts/jd_jl.py", line 344, in main                                                        
    asyncio.run(asyncmain())                                                                            
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run                                         
    return loop.run_until_complete(main)                                                                
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete                     
    return future.result()                                                                              
  File "/jd/scripts/jd_jl.py", line 294, in asyncmain                                                   
    cookie_list_pin=[cookie for cookie in cookie_list if get_pin(cookie) in debug_pin]                  
  File "/jd/scripts/jd_jl.py", line 294, in <listcomp>                                                  
    cookie_list_pin=[cookie for cookie in cookie_list if get_pin(cookie) in debug_pin]                  
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by wuye999** [comment]
字面意思啊，你没填环境变量

**Comment by lhj2525** [comment]
比如锦鲤红包的，我不设置kois的变量随机助力是正常的，但是我在脚本内或者V4的config.sh里添加export kois=“138888888_p”的话就会这个错误。（QAQ）感谢大佬回复

**Comment by wuye999** [comment]
> 比如锦鲤红包的，我不设置kois的变量随机助力是正常的，但是我在脚本内或者V4的config.sh里添加export kois=“138888888_p”的话就会这个错误。（QAQ）感谢大佬回复

还有提示ck不正确吗

**Comment by wuye999** [comment]
而且这个jd_jl.py，我这里没有这样的脚本…

**Comment by lhj2525** [comment]
随机助力的时候也会提示ck不正确，但是能正常跑，jd_jl，是自己改的，跟以前重复名字的做个区别。
<img width="694" alt="WechatIMG1520" src="https://user-images.githubusercontent.com/39327533/141025904-68f06c3e-2227-4ec1-989c-55913b52785b.png">

**Comment by wuye999** [comment]
那就是查看格式不正确了。。。
