### ISSUE TITLE
青龙跑联通，一直在一个地方卡住。

### ISSUE THREAD

**Issue by ryokoberryz** [wuye999/myScripts#20]
## 开始执行... 2021-11-30 17:29:37

unicom_index.py: --------------账号分割线---------------
login.py: 【登录】: 0022
util.py: 【通信积分】: 253
util.py: 【奖励积分】: 1628
util.py: 【定向积分】: 5600
util.py: 【优惠券】: 1
daily_daysign.py: 【每日签到】: 您今天已经签到啦
game_dongao.py: 【东奥积分活动】: 领取失败，已领取请次日在领取
year_end_rewards.py: 【年终亿元回馈】：剩余抽奖次数 0
daily_integral_100.py: 【100定向积分】: 不可重复领取
daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x1
daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x2
daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x3
every_day_redEnvelope.py: 你的抽奖次数已用完
wo_tree.py: 【沃之树-领流量】: 4M流量 x2
wo_tree.py: 【沃之树-领流量】: 4M流量 x4
wo_tree.py: 【沃之树-领流量】: 4M流量 x6
wo_tree.py: 【沃之树-领流量新】: 4M流量 x7
wo_tree.py: 【沃之树-浇水】: 获得0培养值
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb8bb536fd0>: Failed to establish a new connection: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='atp.bol.wo.cn', port=443): Max retries exceeded with url: /atpapi/cuuser/auth/redirect?code=2k1fFq&redirectUrl=https%3A%2F%2Fatp.bol.wo.cn%2Fatplottery%2FACT202009101956022770009xRb2UQ%3FredirectUrl%3Dhttps%3A%2F%2Fatp.bol.wo.cn%2Fatplottery%2FACT202009101956022770009xRb2UQ%26type%3D02%26ticket%3D5dkagza146bc9087c460cc104c637aab7d848495cxncsv06%26version%3Diphone_c%408.0004%26timestamp%3D20211130173029%26desmobile%3D18621570022%26num%3D0%26postage%3D7fc5b7f9a7412ee9e9044c886eb0fb5e%26desmobile%3D18621570022%26product%3Dhfgo%26yw_code%3D%26ch%3D010%26userNumber%3D18621570022&state= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb8bb536fd0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "unicom_index.py", line 276, in <module>
    main_handler("","")
  File "unicom_index.py", line 257, in main_handler
    runTask(client, user)
  File "unicom_index.py", line 177, in runTask
    task_obj.run(client, user)
  File "/ql/scripts/wuye999_myScripts/unicom-task/task/turntable_lottery.py", line 22, in run
    self.openPlatLineNew()  # 获取cookie
  File "/ql/scripts/wuye999_myScripts/unicom-task/task/turntable_lottery.py", line 30, in openPlatLineNew
    res=self.client.get(url)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='atp.bol.wo.cn', port=443): Max retries exceeded with url: /atpapi/cuuser/auth/redirect?code=2k1fFq&redirectUrl=https%3A%2F%2Fatp.bol.wo.cn%2Fatplottery%2FACT202009101956022770009xRb2UQ%3FredirectUrl%3Dhttps%3A%2F%2Fatp.bol.wo.cn%2Fatplottery%2FACT202009101956022770009xRb2UQ%26type%3D02%26ticket%3D5dkagza146bc9087c460cc104c637aab7d848495cxncsv06%26version%3Diphone_c%408.0004%26timestamp%3D20211130173029%26desmobile%3D18621570022%26num%3D0%26postage%3D7fc5b7f9a7412ee9e9044c886eb0fb5e%26desmobile%3D18621570022%26product%3Dhfgo%26yw_code%3D%26ch%3D010%26userNumber%3D18621570022&state= (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb8bb536fd0>: Failed to establish a new connection: [Errno 110] Operation timed out'))

## 执行结束... 2021-11-30 17:32:41 耗时 184 秒

**Comment by wuye999** [comment]
> 

已改，再次拉取尝试

**Comment by ryokoberryz** [comment]
感谢大神，刚跑了下昨天的地方能过了，但天天领现金的脚本有报错，是不是我黑号了？

## 开始执行... 2021-12-01 14:02:04

unicom_index.py: --------------账号分割线---------------
login.py: 【登录】: 0022
util.py: 【通信积分】: 253
util.py: 【奖励积分】: 1628
util.py: 【定向积分】: 6000
util.py: 【优惠券】: 1
daily_daysign.py: 【每日签到】: 您今天已经签到啦
game_dongao.py: 【东奥积分活动】: 领取失败，已领取请次日在领取
year_end_rewards.py: 【年终亿元回馈】：剩余抽奖次数 0
daily_integral_100.py: 【100定向积分】: 不可重复领取
daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x1
daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x2
daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x3
every_day_redEnvelope.py: 你的抽奖次数已用完
wo_tree.py: 【沃之树-领流量】: 已领取过 x2
wo_tree.py: 【沃之树-领流量】: 已领取过 x4
wo_tree.py: 【沃之树-领流量】: 已领取过 x6
wo_tree.py: 【沃之树-领流量】: 已领取过 x8
wo_tree.py: 【沃之树-浇水】: 获得0培养值
turntable_lottery.py: 【转盘抽奖】：登录超时
everyday_way.py: 【天天领现金】：获取rptid失败











<!DOCTYPE html>
<html class="ui-page-login">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no, email=no"/>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>账户存在风险</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            touch-action: none;
            pointer-events: auto;
        }

        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: #94A2B1;
            height: 75%;
            margin: 0;
            padding: 0;
        }

        .baodudu {
            width: 13rem;
        }


        .the_button {
            margin-top: 1.6rem;
            text-align: center;
            padding-left: 2rem;
            padding-right: 2rem;
            /*height: 0.5rem;*/
            /*padding: 0.625rem;*/
            font-size: 0.9rem;
            /* display: block; */
            width: 100%;
            margin-bottom: 0.625rem;
            border: none;
            color: #fff;
            line-height: 1.42;
            height: 2.2rem;
            background-image: linear-gradient(135deg, #FFA033 0%, #FF6D33 100%);
            /*background-image: linear-gradient(45deg, #FFA033 0%, #FF6D33 100%);*/
            box-shadow: 0 0.625rem 1.125rem 0 rgba(255, 158, 51, 0.40);
            border-radius: 2.875rem;
            outline: none;
        }

        .text {
            text-align: center;
            padding: 50px;
        }
    </style>
</head>
<body>
<div class="container">
    <div>
        <img id="baodudu" class="baodudu" src="https://epay.10010.com/woauth2/static/images/baodudu-ufo.png"/>
    </div>
    <div class="text">
        您的操作存在风险，此次操作不成功，如有疑问请联系在线客服
    </div>
    <div>
        <button type="button" class="the_button" id="btn_login">在线客服</button>
    </div>
</div>
<script src="https://epay.10010.com/woauth2/static/js/jquery-3.5.1.min.js"></script>
<script src="https://epay.10010.com/woauth2/static/js/materialize.js"></script>
<script>
    $(function () {
        $("#btn_login").click(function () {
            window.location.href = 'https://service.unicompayment.com/live800/chatClient/chatbox.jsp?companyID=9061&configID=48&pagereferrer=%e8%81%94%e9%80%9a%e6%89%8b%e5%8e%85&chatfrom=shouting&shouting=shouting&entershouting';
        });
    });
</script>
</body>
</html>
everyday_way.py: 【天天领现金】：该用户未登录请登录
everyday_way.py: 【天天领现金】：已经签到过了，或打卡失败
everyday_way.py: 【天天领现金】：前方通道抢修中，请稍后重新登录再试吧~
game_signin.py: 【游戏频道打卡】: 游戏积分领取失败
action_flow.py: 【即将过期流量包】: 暂无

**Comment by wuye999** [comment]
> 感谢大神，刚跑了下昨天的地方能过了，但天天领现金的脚本有报错，是不是我黑号了？
> 
> ## 开始执行... 2021-12-01 14:02:04
> unicom_index.py: --------------账号分割线--------------- login.py: 【登录】: 0022 util.py: 【通信积分】: 253 util.py: 【奖励积分】: 1628 util.py: 【定向积分】: 6000 util.py: 【优惠券】: 1 daily_daysign.py: 【每日签到】: 您今天已经签到啦 game_dongao.py: 【东奥积分活动】: 领取失败，已领取请次日在领取 year_end_rewards.py: 【年终亿元回馈】：剩余抽奖次数 0 daily_integral_100.py: 【100定向积分】: 不可重复领取 daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x1 daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x2 daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x3 every_day_redEnvelope.py: 你的抽奖次数已用完 wo_tree.py: 【沃之树-领流量】: 已领取过 x2 wo_tree.py: 【沃之树-领流量】: 已领取过 x4 wo_tree.py: 【沃之树-领流量】: 已领取过 x6 wo_tree.py: 【沃之树-领流量】: 已领取过 x8 wo_tree.py: 【沃之树-浇水】: 获得0培养值 turntable_lottery.py: 【转盘抽奖】：登录超时 everyday_way.py: 【天天领现金】：获取rptid失败
> 
> <title>账户存在风险</title> <style> html, body { height: 100%; margin: 0; padding: 0; touch-action: none; pointer-events: auto; }
> ```
>     .container {
>         display: flex;
>         flex-direction: column;
>         justify-content: center;
>         align-items: center;
>         color: #94A2B1;
>         height: 75%;
>         margin: 0;
>         padding: 0;
>     }
> 
>     .baodudu {
>         width: 13rem;
>     }
> 
> 
>     .the_button {
>         margin-top: 1.6rem;
>         text-align: center;
>         padding-left: 2rem;
>         padding-right: 2rem;
>         /*height: 0.5rem;*/
>         /*padding: 0.625rem;*/
>         font-size: 0.9rem;
>         /* display: block; */
>         width: 100%;
>         margin-bottom: 0.625rem;
>         border: none;
>         color: #fff;
>         line-height: 1.42;
>         height: 2.2rem;
>         background-image: linear-gradient(135deg, #FFA033 0%, #FF6D33 100%);
>         /*background-image: linear-gradient(45deg, #FFA033 0%, #FF6D33 100%);*/
>         box-shadow: 0 0.625rem 1.125rem 0 rgba(255, 158, 51, 0.40);
>         border-radius: 2.875rem;
>         outline: none;
>     }
> 
>     .text {
>         text-align: center;
>         padding: 50px;
>     }
> </style>
> ```
> 
> ![](https://camo.githubusercontent.com/a5a493e9a4c658ec2e1fef47e532b1e4b41e7cb7dbde716284a16b754fc380e8/68747470733a2f2f657061792e31303031302e636f6d2f776f61757468322f7374617469632f696d616765732f62616f647564752d75666f2e706e67)
> 您的操作存在风险，此次操作不成功，如有疑问请联系在线客服
> 在线客服
> <script src="https://epay.10010.com/woauth2/static/js/jquery-3.5.1.min.js"></script> <script src="https://epay.10010.com/woauth2/static/js/materialize.js"></script> <script> $(function () { $("#btn_login").click(function () { window.location.href = 'https://service.unicompayment.com/live800/chatClient/chatbox.jsp?companyID=9061&configID=48&pagereferrer=%e8%81%94%e9%80%9a%e6%89%8b%e5%8e%85&chatfrom=shouting&shouting=shouting&entershouting'; }); }); </script> everyday_way.py: 【天天领现金】：该用户未登录请登录 everyday_way.py: 【天天领现金】：已经签到过了，或打卡失败 everyday_way.py: 【天天领现金】：前方通道抢修中，请稍后重新登录再试吧~ game_signin.py: 【游戏频道打卡】: 游戏积分领取失败 action_flow.py: 【即将过期流量包】: 暂无

昨天的更新解决了天天领现金打卡问题，更新脚本再次尝试

**Comment by ryokoberryz** [comment]
> > 感谢大神，刚跑了下昨天的地方能过了，但天天领现金的脚本有报错，是不是我黑号了？
> > ## 开始执行... 2021-12-01 14:02:04
> > unicom_index.py: --------------账号分割线--------------- login.py: 【登录】: 0022 util.py: 【通信积分】: 253 util.py: 【奖励积分】: 1628 util.py: 【定向积分】: 6000 util.py: 【优惠券】: 1 daily_daysign.py: 【每日签到】: 您今天已经签到啦 game_dongao.py: 【东奥积分活动】: 领取失败，已领取请次日在领取 year_end_rewards.py: 【年终亿元回馈】：剩余抽奖次数 0 daily_integral_100.py: 【100定向积分】: 不可重复领取 daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x1 daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x2 daily_lottery.py: 【天天抽奖】: 用户机会次数不足 x3 every_day_redEnvelope.py: 你的抽奖次数已用完 wo_tree.py: 【沃之树-领流量】: 已领取过 x2 wo_tree.py: 【沃之树-领流量】: 已领取过 x4 wo_tree.py: 【沃之树-领流量】: 已领取过 x6 wo_tree.py: 【沃之树-领流量】: 已领取过 x8 wo_tree.py: 【沃之树-浇水】: 获得0培养值 turntable_lottery.py: 【转盘抽奖】：登录超时 everyday_way.py: 【天天领现金】：获取rptid失败
> > <title>账户存在风险</title> <style> html, body { height: 100%; margin: 0; padding: 0; touch-action: none; pointer-events: auto; }
> > ```
> >     .container {
> >         display: flex;
> >         flex-direction: column;
> >         justify-content: center;
> >         align-items: center;
> >         color: #94A2B1;
> >         height: 75%;
> >         margin: 0;
> >         padding: 0;
> >     }
> > ```
> > .baodudu {
> >     width: 13rem;
> > }
> > 
> > 
> > .the_button {
> >     margin-top: 1.6rem;
> >     text-align: center;
> >     padding-left: 2rem;
> >     padding-right: 2rem;
> >     /*height: 0.5rem;*/
> >     /*padding: 0.625rem;*/
> >     font-size: 0.9rem;
> >     /* display: block; */
> >     width: 100%;
> >     margin-bottom: 0.625rem;
> >     border: none;
> >     color: #fff;
> >     line-height: 1.42;
> >     height: 2.2rem;
> >     background-image: linear-gradient(135deg, #FFA033 0%, #FF6D33 100%);
> >     /*background-image: linear-gradient(45deg, #FFA033 0%, #FF6D33 100%);*/
> >     box-shadow: 0 0.625rem 1.125rem 0 rgba(255, 158, 51, 0.40);
> >     border-radius: 2.875rem;
> >     outline: none;
> > }
> > 
> > .text {
> >     text-align: center;
> >     padding: 50px;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > </style>
> > ```
> > ![](https://camo.githubusercontent.com/a5a493e9a4c658ec2e1fef47e532b1e4b41e7cb7dbde716284a16b754fc380e8/68747470733a2f2f657061792e31303031302e636f6d2f776f61757468322f7374617469632f696d616765732f62616f647564752d75666f2e706e67)
> > 您的操作存在风险，此次操作不成功，如有疑问请联系在线客服
> > 在线客服
> > <script src="https://epay.10010.com/woauth2/static/js/jquery-3.5.1.min.js"></script> <script src="https://epay.10010.com/woauth2/static/js/materialize.js"></script> <script> $(function () { $("#btn_login").click(function () { window.location.href = 'https://service.unicompayment.com/live800/chatClient/chatbox.jsp?companyID=9061&configID=48&pagereferrer=%e8%81%94%e9%80%9a%e6%89%8b%e5%8e%85&chatfrom=shouting&shouting=shouting&entershouting'; }); }); </script> everyday_way.py: 【天天领现金】：该用户未登录请登录 everyday_way.py: 【天天领现金】：已经签到过了，或打卡失败 everyday_way.py: 【天天领现金】：前方通道抢修中，请稍后重新登录再试吧~ game_signin.py: 【游戏频道打卡】: 游戏积分领取失败 action_flow.py: 【即将过期流量包】: 暂无
> 
> 昨天的更新解决了天天领现金打卡问题，更新脚本再次尝试

今天更新了再跑，还是这个报错

**Comment by wuye999** [comment]
> 

我猜是在不常用ip登录导致的
