### ISSUE TITLE
是不是变量格式填错了。。联通的老是跑不起来的

### ISSUE THREAD

**Issue by a502747245** [wuye999/myScripts#21]
![image](https://user-images.githubusercontent.com/45420905/144215453-1ba6148f-a63b-4f88-b434-5c1dee85dc2a.png)
大佬。。为毛变量按照要求添加了。。跑起来还是报错。。。

## 开始执行... 2021-12-01 18:12:52

Traceback (most recent call last):
  File "wuye999_myScripts_unicom_index.py", line 30, in <module>
    import json,time,re,traceback,random,datetime,util,sys,login,logging
  File "/ql/scripts/unicom-task/task/util.py", line 12, in <module>
    import requests,json,time,re,login,logging,traceback,os,random,datetime
  File "/ql/scripts/unicom-task/task/login.py", line 12, in <module>
    import base64,rsa,time,requests,logging,traceback
ModuleNotFoundError: No module named 'rsa'

## 执行结束... 2021-12-01 18:12:52 耗时 0 秒

**Comment by a502747245** [comment]
![image](https://user-images.githubusercontent.com/45420905/144216063-da82b5cc-baba-47ab-9b9e-8b1734229f03.png)
在配置文件里面也试了一下。。删掉脚本重新拉了也是报上面一样的错误。。。大佬。。求助。。是咋回事。。。。

**Comment by wuye999** [comment]
缺少 rsa模块

**Comment by wuye999** [comment]
> ModuleNotFoundError: No module named 'rsa'

ModuleNotFoundError: No module named 'rsa'

**Comment by a502747245** [comment]
哭了。。是依赖吗。。还是啥。。。

**Comment by wuye999** [comment]
> 哭了。。是依赖吗。。还是啥。。。

缺少rsa模块啊，ModuleNotFoundError: No module named 'rsa' 这里有提示啊，用青龙依赖管理python里安装rsa模块

**Comment by a502747245** [comment]
明白了，谢谢大佬

**Comment by a502747245** [comment]
![image](https://user-images.githubusercontent.com/45420905/144257880-327c00de-d186-4785-a2c5-fff9fee0ab91.png)
这个lxml一直安装失败。。。

**Comment by a502747245** [comment]
依赖是装上去了。。
![image](https://user-images.githubusercontent.com/45420905/144262401-5572cd65-8cc7-4d92-a57d-12065fdaa9f5.png)
空的。。。

**Comment by wuye999** [comment]
> 依赖是装上去了。。 ![image](https://user-images.githubusercontent.com/45420905/144262401-5572cd65-8cc7-4d92-a57d-12065fdaa9f5.png) 空的。。。

这就很奇怪了

**Comment by a502747245** [comment]
![image](https://user-images.githubusercontent.com/45420905/144263202-db08a54f-ac57-4c28-8cb9-d8faf2bc1733.png)
![image](https://user-images.githubusercontent.com/45420905/144263218-54f3c21c-bb6f-4cff-a322-66fc99df4138.png)
依赖全都是装在python里面。。

**Comment by wuye999** [comment]
环境变量没设置吧

**Comment by wuye999** [comment]
> ![image](https://user-images.githubusercontent.com/45420905/144263202-db08a54f-ac57-4c28-8cb9-d8faf2bc1733.png) ![image](https://user-images.githubusercontent.com/45420905/144263218-54f3c21c-bb6f-4cff-a322-66fc99df4138.png) 依赖全都是装在python里面。。

环境变量没设置吧

**Comment by a502747245** [comment]
![image](https://user-images.githubusercontent.com/45420905/144265405-4afb9684-40cf-426d-b391-6d5fa00e3018.png)
在配置文件里面创建是没用的。。。
![image](https://user-images.githubusercontent.com/45420905/144265493-6ee54c9d-6157-49cf-8129-8f1228164b56.png)
在环境变量里面新增变量跑出来的结果是这样的：
## 开始执行... 2021-12-01 23:40:33

wuye999_myScripts_unicom_index.py: --------------账号分割线---------------
login.py: 【登录】: 3123
util.py: 【通信积分】: 2482
util.py: 【奖励积分】: 0
util.py: 【优惠券】: 0
every_day_redEnvelope.py: 抽到 28元美团福利券包
daily_lottery.py: 【天天抽奖】: 谢谢参与~ x1
daily_lottery.py: 【天天抽奖】: 谢谢参与~ x2
daily_lottery.py: 【天天抽奖】: 谢谢参与~ x3
year_end_rewards.py: 【年终亿元回馈】：剩余抽奖次数 5
year_end_rewards.py: 【年终亿元回馈】：抽到 用户未中奖
year_end_rewards.py: 【年终亿元回馈】：抽到 用户未中奖
year_end_rewards.py: 【年终亿元回馈】：抽到 用户未中奖
year_end_rewards.py: 【年终亿元回馈】：抽到 50元大礼包
year_end_rewards.py: 【年终亿元回馈】：抽到 用户未中奖
wo_tree.py: 【沃之树-领流量】: 4M流量 x2
wo_tree.py: 【沃之树-领流量】: 4M流量 x4
wo_tree.py: 【沃之树-领流量】: 4M流量 x6
wo_tree.py: 【沃之树-领流量】: 4M流量 x8
wo_tree.py: 【沃之树-浇水】: 获得3培养值
everyday_way.py: 【天天领现金】：获取rptid失败











<!DOCTYPE html>
<html class="ui-page-login">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black"/>
    <meta name="format-detection" content="telephone=no, email=no"/>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>账户存在风险</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            touch-action: none;
            pointer-events: auto;
        }

        .container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: #94A2B1;
            height: 75%;
            margin: 0;
            padding: 0;
        }

        .baodudu {
            width: 13rem;
        }


        .the_button {
            margin-top: 1.6rem;
            text-align: center;
            padding-left: 2rem;
            padding-right: 2rem;
            /*height: 0.5rem;*/
            /*padding: 0.625rem;*/
            font-size: 0.9rem;
            /* display: block; */
            width: 100%;
            margin-bottom: 0.625rem;
            border: none;
            color: #fff;
            line-height: 1.42;
            height: 2.2rem;
            background-image: linear-gradient(135deg, #FFA033 0%, #FF6D33 100%);
            /*background-image: linear-gradient(45deg, #FFA033 0%, #FF6D33 100%);*/
            box-shadow: 0 0.625rem 1.125rem 0 rgba(255, 158, 51, 0.40);
            border-radius: 2.875rem;
            outline: none;
        }

        .text {
            text-align: center;
            padding: 50px;
        }
    </style>
</head>
<body>
<div class="container">
    <div>
        <img id="baodudu" class="baodudu" src="https://epay.10010.com/woauth2/static/images/baodudu-ufo.png"/>
    </div>
    <div class="text">
        您的操作存在风险，此次操作不成功，如有疑问请联系在线客服
    </div>
    <div>
        <button type="button" class="the_button" id="btn_login">在线客服</button>
    </div>
</div>
<script src="https://epay.10010.com/woauth2/static/js/jquery-3.5.1.min.js"></script>
<script src="https://epay.10010.com/woauth2/static/js/materialize.js"></script>
<script>
    $(function () {
        $("#btn_login").click(function () {
            window.location.href = 'https://service.unicompayment.com/live800/chatClient/chatbox.jsp?companyID=9061&configID=48&pagereferrer=%e8%81%94%e9%80%9a%e6%89%8b%e5%8e%85&chatfrom=shouting&shouting=shouting&entershouting';
        });
    });
</script>
</body>
</html>
everyday_way.py: 【天天领现金】：该用户未登录请登录
everyday_way.py: 【天天领现金】：已经签到过了，或打卡失败
everyday_way.py: 【天天领现金】：前方通道抢修中，请稍后重新登录再试吧~
daily_integral_100.py: 【100定向积分】: 领取成功
game_signin.py: 【游戏频道打卡】: 游戏积分领取失败
turntable_lottery.py: 【转盘抽奖】：登录超时
action_flow.py: 【即将过期流量包】: 暂无
game_dongao.py: 【东奥积分活动】: 领取成功，600积分
daily_daysign.py: 【每日签到】: 打卡成功
api.py: Detected declarative mark in sequence. Priority +1 given for utf_8.
api.py: Code page utf_8 is a multi byte encoding table and it appear that at least one character was encoded using n-bytes.
api.py: utf_8 passed initial chaos probing. Mean measured chaos is 0.000000 %
api.py: We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0), ('Italian', 1.0), ('Dutch', 1.0)] using utf_8
api.py: utf_8 is most likely the one. Stopping the process.
api.py: Detected declarative mark in sequence. Priority +1 given for utf_8.
api.py: Code page utf_8 is a multi byte encoding table and it appear that at least one character was encoded using n-bytes.
api.py: utf_8 passed initial chaos probing. Mean measured chaos is 0.000000 %
api.py: We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0), ('Italian', 1.0), ('Dutch', 1.0)] using utf_8
api.py: utf_8 is most likely the one. Stopping the process.
wuye999_myScripts_unicom_index.py: --------------账号分割线---------------
email_task.py: 【沃邮箱签到】: 已连续签到1天
email_task.py: 【沃邮箱签到】: 已签到
email_task.py: 【沃邮箱每日首次登录】: 任务已做过
email_task.py: 【浅秋领福利】: 任务已做过
email_task.py: 【下载沃邮箱app】: 任务已做过
email_task.py: 【去用户俱乐部逛一逛】: 任务已做过
email_task.py: 【沃邮箱】: 已连续签到 1 天
email_task.py: 【沃邮箱】: 成长值签到结果: 您今天已签到，不可重复签到
email_task.py: 【沃邮箱】: 积分任务出错 
'data'
email_task.py: 【沃邮箱】: 跳过俱乐部签到
email_task.py: 【沃邮箱】: 跳过参与俱乐部活动
email_task.py: 【沃邮箱】: 跳过俱乐部积分兑换
email_task.py: 【沃邮箱】: 跳过俱乐部修改个人资料
email_task.py: 【沃邮箱扩展任务】：未找到沃邮箱手机号或密码
api.py: Detected declarative mark in sequence. Priority +1 given for utf_8.
api.py: Code page utf_8 is a multi byte encoding table and it appear that at least one character was encoded using n-bytes.
api.py: utf_8 passed initial chaos probing. Mean measured chaos is 0.000000 %
api.py: We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0), ('Italian', 1.0), ('Dutch', 1.0)] using utf_8
api.py: utf_8 is most likely the one. Stopping the process.
api.py: Detected declarative mark in sequence. Priority +1 given for utf_8.
api.py: Code page utf_8 is a multi byte encoding table and it appear that at least one character was encoded using n-bytes.
api.py: utf_8 passed initial chaos probing. Mean measured chaos is 0.000000 %
api.py: We detected language [('English', 1.0), ('Indonesian', 1.0), ('Simple English', 1.0), ('Italian', 1.0), ('Dutch', 1.0)] using utf_8
api.py: utf_8 is most likely the one. Stopping the process.

## 执行结束... 2021-12-01 23:42:10 耗时 97 秒

**Comment by a502747245** [comment]
是不是还有哪里设置有问题。。。还是说需要去联通APP哪个地方点什么。。

**Comment by wuye999** [comment]
> 

除了天天领现金，都没问题，天天领现金可能要手动进入一次

**Comment by a502747245** [comment]
在APP上没找到，他是不是隐藏入口了。。。

**Comment by a502747245** [comment]
我的不是这样的，我在首页往下拉找到了。。。点了一下签到，谢了，大佬

**Comment by xinyunya** [comment]
## 开始执行... 2021-12-02 04:21:56

Traceback (most recent call last):
  File "unicom_index.py", line 32, in <module>
    from lxml.html import fromstring
  File "/ql/scripts/wuye999_myScripts/unicom-task/tenscf_rely/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: cannot import name 'etree' from 'lxml' (/ql/scripts/wuye999_myScripts/unicom-task/tenscf_rely/lxml/__init__.py)

## 执行结束... 2021-12-02 04:21:56 耗时 0 秒

大佬，我的显示这样是不是依赖的原因啊，更新pip后lxml还是安装失败，最后两行显示错误
   Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by wuye999** [comment]
> 

你是手动下载了项目放进去的吗，还是青龙命令拉取的啊

**Comment by xinyunya** [comment]
青龙拉取的命令

**Comment by wuye999** [comment]
> 青龙拉取的命令

![image](https://user-images.githubusercontent.com/79479594/144360925-d0b9b4fa-f369-4d52-9cc5-3ce2057f272c.png)

**Comment by xinyunya** [comment]
手动下载放入也还是显示一样的

**Comment by wuye999** [comment]
> 手动下载放入也还是显示一样的

升级pip,然后安装lxml吧

**Comment by xinyunya** [comment]
开始安装依赖 lxml，开始时间 2021/12/2 下午4:33:20

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple

Collecting lxml

  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fe/4c/a4dbb4e389f75e69dbfb623462dfe0d0e652107a95481d40084830d29b37/lxml-4.6.4.tar.gz (3.2 MB)

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cu8085tj/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cu8085tj/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rj1f77j3
         cwd: /tmp/pip-install-cu8085tj/lxml/
    Complete output (3 lines):
    Building lxml version 4.6.4.
    Building without Cython.
    Error: Please make sure the libxml2 and libxslt development packages are installed.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

依赖安装失败，结束时间 2021/12/2 下午4:33:27，耗时 7.384 秒

更新了pip，lxml安装失败了

**Comment by wuye999** [comment]
> 

我不太懂是怎么回事

**Comment by xinyunya** [comment]
> > 
> 
> 我不太懂是怎么回事

我先换云函数运行了了，感谢大佬指点拉

**Comment by jyiwbb** [comment]
> ![image](https://user-images.githubusercontent.com/45420905/144215453-1ba6148f-a63b-4f88-b434-5c1dee85dc2a.png) 大佬。。为毛变量按照要求添加了。。跑起来还是报错。。。
> 
> ## 开始执行... 2021-12-01 18:12:52
> Traceback (most recent call last): File "wuye999_myScripts_unicom_index.py", line 30, in import json,time,re,traceback,random,datetime,util,sys,login,logging File "/ql/scripts/unicom-task/task/util.py", line 12, in import requests,json,time,re,login,logging,traceback,os,random,datetime File "/ql/scripts/unicom-task/task/login.py", line 12, in import base64,rsa,time,requests,logging,traceback ModuleNotFoundError: No module named 'rsa'
> 
> ## 执行结束... 2021-12-01 18:12:52 耗时 0 秒

您好，联通wo邮箱登录的url是怎么获取的我登录公众号的url和你的不一样。
