### ISSUE TITLE
请求大佬帮助；运行到这里就退出了

### ISSUE THREAD

**Issue by nomoneynolife** [wuye999/myScripts#22]
o_tree.py: 【沃之树-领流量】: 已领取过 x8
wo_tree.py: 【沃之树-浇水】: 获得0培养值
year_end_rewards.py: 【年终亿元回馈】：剩余抽奖次数 0
获取通知服务失败，请检查网络连接...
获取通知服务失败，请检查网络连接...
Traceback (most recent call last):
  File "unicom_index.py", line 220, in main
    initialize(d)
  File "/ql/scripts/unicom-task/./utils/sendNotify.py", line 53, in initialize
    elif push_config[push_key]:
KeyError: 'BARK_PUSH'

During handling of the above exception, another exception occurred:

然后就退出了，

**Comment by nomoneynolife** [comment]
我是青龙跑的，

**Comment by nomoneynolife** [comment]
重拉就好了，无语~
