### ISSUE TITLE
大佬 更新后报错了

### ISSUE THREAD

**Issue by kyw9966** [wuye999/myScripts#23]
Traceback (most recent call last):
  File "/ql/repo/wuye999_myScripts/unicom-task/unicom_index.py", line 271, in <module>
    main_handler("","")
  File "/ql/repo/wuye999_myScripts/unicom-task/unicom_index.py", line 252, in main_handler
    runTask(client, user)
  File "/ql/repo/wuye999_myScripts/unicom-task/unicom_index.py", line 176, in runTask
    task_class = getattr(task_module, entry.name[0:-3])
AttributeError: module 'task.sendNotify' has no attribute 'sendNotify'

**Comment by wuye999** [comment]
删除unicom-task/task/sendNotify.py unicom-task/task/login.py unicom-task/task/util.py

**Comment by goden-er** [comment]
大佬，看一下这个错误。[https://z3.ax1x.com/2021/12/03/odSxAK.png](url)

**Comment by wuye999** [comment]
> 

更新一下试试，bug确实有点多

**Comment by wuye999** [comment]
> 大佬，看一下这个错误。[https://z3.ax1x.com/2021/12/03/odSxAK.png](url)，楼上的那个文件删除了还是一样

这个链接打不开

**Comment by goden-er** [comment]
> 

![image](https://user-images.githubusercontent.com/60930469/144608055-84b4d7b0-4fd2-4259-b3a9-b8bc9ea0a839.png)

**Comment by goden-er** [comment]
> > 
> 
> 更新一下试试，bug确实有点多
更新过了产生的问题

**Comment by wuye999** [comment]
> > > 
> > 
> > 
> > 更新一下试试，bug确实有点多
> > 更新过了产生的问题

你看一下login.py里有这个函数吗
![image](https://user-images.githubusercontent.com/79479594/144608412-937154c3-95b2-43f5-b4ed-ca26444be9d7.png)

**Comment by goden-er** [comment]
> > > > 
> > > 
> > > 
> > > 更新一下试试，bug确实有点多
> > > 更新过了产生的问题
> 
> 你看一下login.py里有这个函数吗 ![image](https://user-images.githubusercontent.com/79479594/144608412-937154c3-95b2-43f5-b4ed-ca26444be9d7.png)

有的
![image](https://user-images.githubusercontent.com/60930469/144608976-0713f345-1b48-4e90-8566-5c33b3cd91a7.png)

**Comment by goden-er** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 更新一下试试，bug确实有点多
> > > > > 更新过了产生的问题
> > > 
> > > 
> > > 你看一下login.py里有这个函数吗 ![image](https://user-images.githubusercontent.com/79479594/144608412-937154c3-95b2-43f5-b4ed-ca26444be9d7.png)
> > 
> > 
> > 有的 ![image](https://user-images.githubusercontent.com/60930469/144608976-0713f345-1b48-4e90-8566-5c33b3cd91a7.png)
> 
> ![image](https://user-images.githubusercontent.com/79479594/144609649-c59187dd-421f-43b5-a3d3-6bc367d2e10b.png) 是py执行的吗

是的

**Comment by wuye999** [comment]
> unicom-task/task/login.py

你看看task文件夹下是不是有login.py啊

**Comment by goden-er** [comment]
> 

也有的，另外我把你项目下载本地运行仍然是login.py里面的59行断掉了
![image](https://user-images.githubusercontent.com/60930469/144611303-66cb0587-dd96-49d1-aade-3b060c07d624.png)
![image](https://user-images.githubusercontent.com/60930469/144611358-1494ce50-df19-489b-b303-28e6ca75d502.png)

**Comment by wuye999** [comment]
> > 
> 
> 也有的，另外我把你项目下载本地运行仍然是login.py里面的59行断掉了 ![image](https://user-images.githubusercontent.com/60930469/144611303-66cb0587-dd96-49d1-aade-3b060c07d624.png) ![image](https://user-images.githubusercontent.com/60930469/144611358-1494ce50-df19-489b-b303-28e6ca75d502.png)

task里的login.py是旧的，青龙拉取后没有删除旧文件，我的项目的task里没有login.py，util.py，sendNotify.py，action_flow.py

**Comment by wuye999** [comment]
> > > 
> > 
> > 
> > 也有的，另外我把你项目下载本地运行仍然是login.py里面的59行断掉了 ![image](https://user-images.githubusercontent.com/60930469/144611303-66cb0587-dd96-49d1-aade-3b060c07d624.png) ![image](https://user-images.githubusercontent.com/60930469/144611358-1494ce50-df19-489b-b303-28e6ca75d502.png)
> 
> task里的login.py是旧的，青龙拉取后没有删除旧文件，我的项目的task里没有login.py，util.py，sendNotify.py，action_flow.py

login.py，util.py，sendNotify.py应该在utlis

**Comment by goden-er** [comment]
> > > > 
> > > 
> > > 
> > > 也有的，另外我把你项目下载本地运行仍然是login.py里面的59行断掉了 ![image](https://user-images.githubusercontent.com/60930469/144611303-66cb0587-dd96-49d1-aade-3b060c07d624.png) ![image](https://user-images.githubusercontent.com/60930469/144611358-1494ce50-df19-489b-b303-28e6ca75d502.png)
> > 
> > 
> > task里的login.py是旧的，青龙拉取后没有删除旧文件，我的项目的task里没有login.py，util.py，sendNotify.py，action_flow.py
> 
> login.py，util.py，sendNotify.py应该在utlis, 你应该删除task下login.py，util.py，sendNotify.py，action_flow.py

那我删除重新拉取一下试试

**Comment by goden-er** [comment]
可以了，但是最后还是有一点报错
![image](https://user-images.githubusercontent.com/60930469/144613320-b0bce09b-97c3-487e-94f6-0476a8015c76.png)

**Comment by wuye999** [comment]
> 



> 可以了，但是最后还是有一点报错 ![image](https://user-images.githubusercontent.com/60930469/144613320-b0bce09b-97c3-487e-94f6-0476a8015c76.png)

这个还在写，还是个半成品

**Comment by goden-er** [comment]
> > 
> 
> > 可以了，但是最后还是有一点报错 ![image](https://user-images.githubusercontent.com/60930469/144613320-b0bce09b-97c3-487e-94f6-0476a8015c76.png)
> 
> 这个还在写，还是个半成品

好的，感谢开发者回复
