### ISSUE TITLE
最新版报错

### ISSUE THREAD

**Issue by xream** [wuye999/myScripts#27]
## 开始执行... 2021-12-04 09:06:28

wuye999_myScripts_unicom_index.py: --------------账号分割线---------------
login.py: 未找到cookie
login.py: 未找到cookie
login.py: 【账号密码登录】: 186********
login.py: 保存cookie成功
login.py: 保存cookie成功
util.py: 【通信积分】: 5
util.py: 【奖励积分】: 2431
util.py: 【定向积分】: 18680
util.py: 【优惠券】: 2
login.py: 未找到cookie
Traceback (most recent call last):
  File "wuye999_myScripts_unicom_index.py", line 288, in <module>
    main_handler("","")
  File "wuye999_myScripts_unicom_index.py", line 269, in main_handler
    runTask(client, user)
  File "wuye999_myScripts_unicom_index.py", line 194, in runTask
    for task_name in task_list:
TypeError: 'NoneType' object is not iterable

## 执行结束... 2021-12-04 09:06:30 耗时 2 秒

**Comment by wuye999** [comment]
看看utlis/task_list.json里面是怎么样的

**Comment by wuye999** [comment]
> 看看utlis/task_list.json里面是怎么样的

看看utlis/task_list.json里面是怎么样的

**Comment by xream** [comment]
明白了 青龙配置里没加 json 我现在改成这样就ok了

```
## ql repo命令拉取脚本时需要拉取的文件后缀，直接写文件后缀名即可
RepoFileExtensions="js py sh ts json"
```

**Comment by wuye999** [comment]
> 明白了 青龙配置里没加 json 我现在改成这样就ok了
> 
> ```
> ## ql repo命令拉取脚本时需要拉取的文件后缀，直接写文件后缀名即可
> RepoFileExtensions="js py sh ts json"
> ```


这确实没想到，我得改下代码修这个问题了

**Comment by xream** [comment]
我还发现一个问题 每次执行都会重新用密码登录

```
login.py: 【cookie登录】 186******** 
login.py: cookie已失效
login.py: 【账号密码登录】: 186********
login.py: 保存cookie成功
login.py: 保存cookie成功
```

**Comment by wuye999** [comment]
> 我还发现一个问题 每次执行都会重新用密码登录
> 
> ```
> login.py: 【cookie登录】 186******** 
> login.py: cookie已失效
> login.py: 【账号密码登录】: 186********
> login.py: 保存cookie成功
> login.py: 保存cookie成功
> ```

这我没有出现这个问题，我猜是使用随机imei导致的，联通会根据这个判断是否登录多台设备，等我更新随机imei的逻辑吧，或者先用固定的imei应该可以解决频繁登录问题

**Comment by wuye999** [comment]
> 

![image](https://user-images.githubusercontent.com/79479594/144692585-a0e4e7da-6962-4581-9f60-3feb98f05954.png)
