### ISSUE TITLE
最新脚本跑不起来

### ISSUE THREAD

**Issue by a1an12** [wuye999/myScripts#32]
## 开始执行... 2021-12-06 21:33:06

Traceback (most recent call last):
  File "unicom_index.py", line 41, in <module>
    import json,time,re,traceback,random,datetime,util,sys,login,logging,importlib,urllib
  File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/util.py", line 6, in <module>
    import requests,json,time,re,login,logging,traceback,os,random,datetime
  File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/login.py", line 5, in <module>
    import base64,rsa,time,requests,logging,traceback,random,json,execjs
ModuleNotFoundError: No module named 'execjs'

## 执行结束... 2021-12-06 21:33:06 耗时 0 秒

依赖管理Nodejs 已添加execjs  还是这样。

**Comment by wuye999** [comment]
> 

我这是python脚本，你安装的是js依赖，你应该在依赖管理Python3安装

> ## 开始执行... 2021-12-06 21:33:06
> Traceback (most recent call last): File "unicom_index.py", line 41, in import json,time,re,traceback,random,datetime,util,sys,login,logging,importlib,urllib File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/util.py", line 6, in import requests,json,time,re,login,logging,traceback,os,random,datetime File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/login.py", line 5, in import base64,rsa,time,requests,logging,traceback,random,json,execjs ModuleNotFoundError: No module named 'execjs'
> 
> ## 执行结束... 2021-12-06 21:33:06 耗时 0 秒
> 依赖管理Nodejs 已添加execjs 还是这样。



> ## 开始执行... 2021-12-06 21:33:06
> Traceback (most recent call last): File "unicom_index.py", line 41, in import json,time,re,traceback,random,datetime,util,sys,login,logging,importlib,urllib File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/util.py", line 6, in import requests,json,time,re,login,logging,traceback,os,random,datetime File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/login.py", line 5, in import base64,rsa,time,requests,logging,traceback,random,json,execjs ModuleNotFoundError: No module named 'execjs'
> 
> ## 执行结束... 2021-12-06 21:33:06 耗时 0 秒
> 依赖管理Nodejs 已添加execjs 还是这样。

我这是python脚本，你安装的是js依赖，你应该在依赖管理Python3安装

**Comment by wuye999** [comment]
> ## 开始执行... 2021-12-06 21:33:06
> Traceback (most recent call last): File "unicom_index.py", line 41, in import json,time,re,traceback,random,datetime,util,sys,login,logging,importlib,urllib File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/util.py", line 6, in import requests,json,time,re,login,logging,traceback,os,random,datetime File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/login.py", line 5, in import base64,rsa,time,requests,logging,traceback,random,json,execjs ModuleNotFoundError: No module named 'execjs'
> 
> ## 执行结束... 2021-12-06 21:33:06 耗时 0 秒
> 依赖管理Nodejs 已添加execjs 还是这样。

我这是python脚本，你安装的是js依赖，你应该在依赖管理Python3安装

**Comment by a1an12** [comment]
python3安装哪个依赖？execjs装不上

**Comment by wuye999** [comment]
> python3安装哪个依赖？execjs装不上

缺少execjs模块, 请执行命令：pip3 install PyExecJS
缺少Cryptodome模块, 请执行命令：pip3 install pycryptodomex
导入 pytz,requests,rsa 模块

**Comment by a1an12** [comment]
谢谢作者解答，已解决。
