### ISSUE TITLE
年终奖的脚本报错

### ISSUE THREAD

**Issue by le2yun** [wuye999/myScripts#33]
Traceback (most recent call last):
  File "/ql/scripts/raw_jd_jd_golden_yearendBonus.py", line 215, in author_helpcode
    response = requests.get(url,timeout=10).json()
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 649, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 742, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for "(0, 'https://mirror.ghproxy.com/https://raw.githubusercontent.com/wuye999/myScripts/main/jd/helpcode/helpcode.json')"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/scripts/raw_jd_jd_golden_yearendBonus.py", line 260, in <module>
    main()
  File "/ql/scripts/raw_jd_jd_golden_yearendBonus.py", line 249, in main
    author_helpcode(cookie)
  File "/ql/scripts/raw_jd_jd_golden_yearendBonus.py", line 218, in author_helpcode
    if e >= (len(url_list)-1):
UnboundLocalError: local variable 'e' referenced before assignment

**Comment by wuye999** [comment]
这是你那个地区ghproxy的cdn没更新，拉到的是旧脚本，过半小时再拉，或者手动下载脚本放进去运行，而且,活动似乎已经没了

**Comment by le2yun** [comment]
啊  不是到12号吗

**Comment by wuye999** [comment]
> 啊 不是到12号吗

可能是京东在做活动调整，加验证啥的，现在手动都进不去活动，试试吧
