### ISSUE TITLE
大佬 最新版拉下来报错了

### ISSUE THREAD

**Issue by kyw9966** [wuye999/myScripts#35]
Traceback (most recent call last):
  File "/ql/repo/wuye999_myScripts/unicom-task/unicom_index.py", line 305, in <module>
    main_handler("","")
  File "/ql/repo/wuye999_myScripts/unicom-task/unicom_index.py", line 286, in main_handler
    runTask(client, user)
  File "/ql/repo/wuye999_myScripts/unicom-task/unicom_index.py", line 210, in runTask
    task_module = importlib.import_module('task.'+task_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/ql/repo/wuye999_myScripts/unicom-task/task/blindBox.py", line 9, in <module>
    from utils.toutiao_reward import TouTiao
  File "/ql/repo/wuye999_myScripts/unicom-task/utils/toutiao_reward.py", line 5, in <module>
    from utils.toutiao_sdk import cbc_encrypt, cbc_decrypt, create_key_iv, md5
  File "/ql/repo/wuye999_myScripts/unicom-task/utils/toutiao_sdk.py", line 6, in <module>
    from Cryptodome.Cipher import AES
  File "/ql/scripts/unicom-task/./tenscf_rely/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/ql/scripts/unicom-task/./tenscf_rely/Cryptodome/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "/ql/scripts/unicom-task/./tenscf_rely/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cpython-38-aarch64-linux-gnu.so', Cannot load '_raw_ecb.abi3.so': Error relocating /ql/scripts/unicom-task/tenscf_rely/Cryptodome/Util/../Cipher/_raw_ecb.abi3.so: unsupported relocation type 8, Not found '_raw_ecb.so'

**Comment by 3418359665** [comment]
ERROR RequestId:f7b8a752-ce67-4dfd-ad2d-27d36e18858f Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/unicom_index.py\", line 286, in main_handler\n    runTask(client, user)\n  File \"/var/user/unicom_index.py\", line 210, in runTask\n    task_module = importlib.import_module('task.'+task_name)\n  File \"/var/lang/python3/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 978, in _gcd_import\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 961, in _find_and_load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 950, in _find_and_load_unlocked\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/task/blindBox.py\", line 9, in \u003cmodule\u003e\n    from utils.toutiao_reward import TouTiao\n  File \"/var/user/utils/toutiao_reward.py\", line 5, in \u003cmodule\u003e\n    from utils.toutiao_sdk import cbc_encrypt, cbc_decrypt, create_key_iv, md5\n  File \"/var/user/utils/toutiao_sdk.py\", line 6, in \u003cmodule\u003e\n    from Cryptodome.Cipher import AES\n  File \"./tenscf_rely/Cryptodome/Cipher/__init__.py\", line 28, in \u003cmodule\u003e\n    from Cryptodome.Cipher._mode_cbc import _create_cbc_cipher\n  File \"./tenscf_rely/Cryptodome/Cipher/_mode_cbc.py\", line 59, in \u003cmodule\u003e\n    \"\"\"\n  File \"./tenscf_rely/Cryptodome/Util/_raw_api.py\", line 309, in load_pycryptodome_raw_lib\n    raise OSError(\"Cannot load native module '%s': %s\" % (name, \", \".join(attempts)))\nOSError: Cannot load native module 'Cryptodome.Cipher._raw_cbc': Not found '_raw_cbc.cpython-36m-x86_64-linux-gnu.so', Cannot load '_raw_cbc.abi3.so': cannot load library '/var/user/tenscf_rely/Cryptodome/Util/../Cipher/_raw_cbc.abi3.so': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/var/user/tenscf_rely/Cryptodome/Util/../Cipher/_raw_cbc.abi3.so', Not found '_raw_cbc.so'","statusCode":430}

END RequestId:f7b8a752-ce67-4dfd-ad2d-27d36e18858f

Report RequestId:f7b8a752-ce67-4dfd-ad2d-27d36e18858f Duration:1522ms Memory:512MB MemUsage:38.753906MB

**Comment by 3418359665** [comment]
云函数报错

**Comment by johnleuang** [comment]
一样，请问问题解决了吗？

**Comment by wuye999** [comment]
确少pycryptodomex模块

**Comment by kyw9966** [comment]
> 确少pycryptodomex模块

谢谢大佬 装好模块后正常了
