### ISSUE TITLE
大佬你好，遇到问题求救

### ISSUE THREAD

**Issue by prcxu** [wuye999/myScripts#36]
日志-联通日常任务
## 开始执行... 2021-12-08 16:35:09

main_handler: --------------账号分割线---------------
onLine: 【cookie登录】 176******** 
onLine: 【cookie登录】 成功
saveData: 保存数据成功
getIntegral: 【通信积分】: 324
getIntegral: 【奖励积分】: 365
getIntegral: 【优惠券】: 0
Traceback (most recent call last):
  File "/ql/scripts/wuye999_myScripts/unicom_index.py", line 305, in <module>
    main_handler("","")
  File "/ql/scripts/wuye999_myScripts/unicom_index.py", line 286, in main_handler
    runTask(client, user)
  File "/ql/scripts/wuye999_myScripts/unicom_index.py", line 210, in runTask
    task_module = importlib.import_module('task.'+task_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/ql/scripts/wuye999_myScripts/unicom-task/task/blindBox.py", line 9, in <module>
    from utils.toutiao_reward import TouTiao
  File "/ql/scripts/wuye999_myScripts/unicom-task/utils/toutiao_reward.py", line 5, in <module>
    from utils.toutiao_sdk import cbc_encrypt, cbc_decrypt, create_key_iv, md5
  File "/ql/scripts/wuye999_myScripts/unicom-task/utils/toutiao_sdk.py", line 6, in <module>
    from Cryptodome.Cipher import AES
  File "/ql/scripts/wuye999_myScripts/unicom-task/./tenscf_rely/Cryptodome/Cipher/__init__.py", line 27, in <module>
    from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
  File "/ql/scripts/wuye999_myScripts/unicom-task/./tenscf_rely/Cryptodome/Cipher/_mode_ecb.py", line 35, in <module>
    raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
  File "/ql/scripts/wuye999_myScripts/unicom-task/./tenscf_rely/Cryptodome/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Not found '_raw_ecb.cpython-39-x86_64-linux-musl.so', Not found '_raw_ecb.abi3.so', Not found '_raw_ecb.so'

**Comment by johnleuang** [comment]
一样，请问问题解决了吗？

**Comment by goden-er** [comment]
一样问题解决了吗？

**Comment by kyw9966** [comment]
一样的问题

**Comment by wuye999** [comment]
确少pycryptodomex模块

**Comment by kyw9966** [comment]
> 

谢谢大佬  装好模块后正常了
