### ISSUE TITLE
大佬，青龙脚本一直 跑不起来，一直提示缺少数据文件，啥情况啊，重新拉库好多次了

### ISSUE THREAD

**Issue by immaiker911** [wuye999/myScripts#43]
## 开始执行... 2021-12-21 00:25:07

main_handler: --------------账号分割线---------------
readData: 数据文件不存在
Traceback (most recent call last):
  File "unicom_index.py", line 298, in <module>
    main_handler("","")
  File "unicom_index.py", line 276, in main_handler
    client = login.get_loginSession(user['username'],user['password'],user['appId'],user['imei'])
  File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/login.py", line 153, in get_loginSession
    session=login(username,password,appId,imei)
  File "/ql/scripts/wuye999_myScripts/unicom-task/./utils/login.py", line 60, in login
    response = session.post('https://m.client.10010.com/mobileService/login.htm', headers=headers, data=data)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1293, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.8/http/client.py", line 1225, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-12: ordinal not in range(256)

## 执行结束... 2021-12-21 00:25:08 耗时 1 秒

**Comment by xiasongmin1** [comment]
同样问题
